# Generated by Django 5.0.6 on 2024-07-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animebooks',
            name='pages',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
